/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdCanvasRouteImport } from './routes/projects.$id.canvas'
import { Route as ProjectsIdExportRouteImport } from './routes/projects.$id.export'
import { Route as ProjectsIdFloorSetupRouteImport } from './routes/projects.$id.floor-setup'
import { Route as ProjectsIdIntakeRouteImport } from './routes/projects.$id.intake'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdCanvasRoute = ProjectsIdCanvasRouteImport.update({
  id: '/projects/$id/canvas',
  path: '/projects/$id/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdExportRoute = ProjectsIdExportRouteImport.update({
  id: '/projects/$id/export',
  path: '/projects/$id/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdFloorSetupRoute = ProjectsIdFloorSetupRouteImport.update({
  id: '/projects/$id/floor-setup',
  path: '/projects/$id/floor-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIntakeRoute = ProjectsIdIntakeRouteImport.update({
  id: '/projects/$id/intake',
  path: '/projects/$id/intake',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/canvas': typeof ProjectsIdCanvasRoute
  '/projects/$id/export': typeof ProjectsIdExportRoute
  '/projects/$id/floor-setup': typeof ProjectsIdFloorSetupRoute
  '/projects/$id/intake': typeof ProjectsIdIntakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/canvas': typeof ProjectsIdCanvasRoute
  '/projects/$id/export': typeof ProjectsIdExportRoute
  '/projects/$id/floor-setup': typeof ProjectsIdFloorSetupRoute
  '/projects/$id/intake': typeof ProjectsIdIntakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/canvas': typeof ProjectsIdCanvasRoute
  '/projects/$id/export': typeof ProjectsIdExportRoute
  '/projects/$id/floor-setup': typeof ProjectsIdFloorSetupRoute
  '/projects/$id/intake': typeof ProjectsIdIntakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects/'
    | '/projects/$id/canvas'
    | '/projects/$id/export'
    | '/projects/$id/floor-setup'
    | '/projects/$id/intake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects'
    | '/projects/$id/canvas'
    | '/projects/$id/export'
    | '/projects/$id/floor-setup'
    | '/projects/$id/intake'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/projects/'
    | '/projects/$id/canvas'
    | '/projects/$id/export'
    | '/projects/$id/floor-setup'
    | '/projects/$id/intake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdCanvasRoute: typeof ProjectsIdCanvasRoute
  ProjectsIdExportRoute: typeof ProjectsIdExportRoute
  ProjectsIdFloorSetupRoute: typeof ProjectsIdFloorSetupRoute
  ProjectsIdIntakeRoute: typeof ProjectsIdIntakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/canvas': {
      id: '/projects/$id/canvas'
      path: '/projects/$id/canvas'
      fullPath: '/projects/$id/canvas'
      preLoaderRoute: typeof ProjectsIdCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/export': {
      id: '/projects/$id/export'
      path: '/projects/$id/export'
      fullPath: '/projects/$id/export'
      preLoaderRoute: typeof ProjectsIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/floor-setup': {
      id: '/projects/$id/floor-setup'
      path: '/projects/$id/floor-setup'
      fullPath: '/projects/$id/floor-setup'
      preLoaderRoute: typeof ProjectsIdFloorSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/intake': {
      id: '/projects/$id/intake'
      path: '/projects/$id/intake'
      fullPath: '/projects/$id/intake'
      preLoaderRoute: typeof ProjectsIdIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdCanvasRoute: ProjectsIdCanvasRoute,
  ProjectsIdExportRoute: ProjectsIdExportRoute,
  ProjectsIdFloorSetupRoute: ProjectsIdFloorSetupRoute,
  ProjectsIdIntakeRoute: ProjectsIdIntakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
